[firebase]
api_key = "AIzaSyA7y8QSa4lCfUejU87ZUj2s0FewE3huw40"
auth_domain = "adf-check.firebaseapp.com"
project_id = "adf-check"
storage_bucket = "adf-check.firebasestorage.app"
messaging_sender_id = "109556990859"
app_id = "1:109556990859:web:2b48cf3c56ac2470c0658e"
measurement_id = "G-2MHPBQV1QS"

